"""first attempt

Revision ID: 0af868b75b7c
Revises: 
Create Date: 2025-08-29 19:54:01.957816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af868b75b7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Capacitors', 'MinVoltage',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('IX_Capacitors_Kind_ID'), table_name='Capacitors')
    op.drop_index(op.f('IX_Capacitors_ManufacturerName_ID'), table_name='Capacitors')
    op.drop_index(op.f('IX_Capacitors_Type_ID'), table_name='Capacitors')
    op.alter_column('ComponentKinds', 'RuComponentKind',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('ComponentKinds', 'EnComponentKind',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('ComponentTypes', 'RuComponentType',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('ComponentTypes', 'EnComponentType',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('Diods', 'RadiationResistanceI',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'QualicationSG',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'QualicationЕС',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'Package',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'Remark1',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'Remark2',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.drop_index(op.f('IX_Diods_Kind_ID'), table_name='Diods')
    op.drop_index(op.f('IX_Diods_ManufacturerName_ID'), table_name='Diods')
    op.drop_index(op.f('IX_Diods_Type_ID'), table_name='Diods')
    op.alter_column('Manufacturers', 'ManufacturerName',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('Microchips', 'Interfaces',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'BitDepthValue',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'TechnologyName_ID',
               existing_type=sa.INTEGER(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('Microchips', 'RadiationResistanceI',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'MemoryFormat',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'Package',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'Qualication',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'Remark1',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.drop_index(op.f('IX_Microchips_Kind_ID'), table_name='Microchips')
    op.drop_index(op.f('IX_Microchips_ManufacturerName_ID'), table_name='Microchips')
    op.drop_index(op.f('IX_Microchips_TechnologyName_ID'), table_name='Microchips')
    op.drop_index(op.f('IX_Microchips_Type_ID'), table_name='Microchips')
    op.drop_constraint(op.f('FK_Microchips_Manufacturers_ManufacturerName_ID'), 'Microchips', type_='foreignkey')
    op.drop_constraint(op.f('FK_Microchips_ComponentKinds_Kind_ID'), 'Microchips', type_='foreignkey')
    op.drop_constraint(op.f('FK_Microchips_ComponentTypes_Type_ID'), 'Microchips', type_='foreignkey')
    op.drop_constraint(op.f('FK_Microchips_Technologies_TechnologyName_ID'), 'Microchips', type_='foreignkey')
    op.create_foreign_key(None, 'Microchips', 'ComponentKinds', ['Kind_ID'], ['ID'])
    op.create_foreign_key(None, 'Microchips', 'ComponentTypes', ['Type_ID'], ['ID'])
    op.create_foreign_key(None, 'Microchips', 'Technologies', ['TechnologyName_ID'], ['ID'])
    op.create_foreign_key(None, 'Microchips', 'Manufacturers', ['ManufacturerName_ID'], ['ID'])
    op.alter_column('Resistors', 'Package',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'QualicationSG',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'QualicationЕС',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'Remark1',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'Remark2',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.drop_index(op.f('IX_Resistors_Kind_ID'), table_name='Resistors')
    op.drop_index(op.f('IX_Resistors_ManufacturerName_ID'), table_name='Resistors')
    op.drop_index(op.f('IX_Resistors_Type_ID'), table_name='Resistors')
    op.alter_column('Technologies', 'RuTechnologyName',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('Technologies', 'EnTechnologyName',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=True)
    op.alter_column('Transistors', 'RadiationResistanceI',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'QualicationSG',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'QualicationЕС',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'Package',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'Remark1',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'Remark2',
               existing_type=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.drop_index(op.f('IX_Transistors_Kind_ID'), table_name='Transistors')
    op.drop_index(op.f('IX_Transistors_ManufacturerName_ID'), table_name='Transistors')
    op.drop_index(op.f('IX_Transistors_Type_ID'), table_name='Transistors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('IX_Transistors_Type_ID'), 'Transistors', ['Type_ID'], unique=False)
    op.create_index(op.f('IX_Transistors_ManufacturerName_ID'), 'Transistors', ['ManufacturerName_ID'], unique=False)
    op.create_index(op.f('IX_Transistors_Kind_ID'), 'Transistors', ['Kind_ID'], unique=False)
    op.alter_column('Transistors', 'Remark2',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'Remark1',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'Package',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'QualicationЕС',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'QualicationSG',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Transistors', 'RadiationResistanceI',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Technologies', 'EnTechnologyName',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.alter_column('Technologies', 'RuTechnologyName',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.create_index(op.f('IX_Resistors_Type_ID'), 'Resistors', ['Type_ID'], unique=False)
    op.create_index(op.f('IX_Resistors_ManufacturerName_ID'), 'Resistors', ['ManufacturerName_ID'], unique=False)
    op.create_index(op.f('IX_Resistors_Kind_ID'), 'Resistors', ['Kind_ID'], unique=False)
    op.alter_column('Resistors', 'Remark2',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'Remark1',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'QualicationЕС',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'QualicationSG',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Resistors', 'Package',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.drop_constraint(None, 'Microchips', type_='foreignkey')
    op.drop_constraint(None, 'Microchips', type_='foreignkey')
    op.drop_constraint(None, 'Microchips', type_='foreignkey')
    op.drop_constraint(None, 'Microchips', type_='foreignkey')
    op.create_foreign_key(op.f('FK_Microchips_Technologies_TechnologyName_ID'), 'Microchips', 'Technologies', ['TechnologyName_ID'], ['ID'], ondelete='CASCADE')
    op.create_foreign_key(op.f('FK_Microchips_ComponentTypes_Type_ID'), 'Microchips', 'ComponentTypes', ['Type_ID'], ['ID'], ondelete='CASCADE')
    op.create_foreign_key(op.f('FK_Microchips_ComponentKinds_Kind_ID'), 'Microchips', 'ComponentKinds', ['Kind_ID'], ['ID'], ondelete='CASCADE')
    op.create_foreign_key(op.f('FK_Microchips_Manufacturers_ManufacturerName_ID'), 'Microchips', 'Manufacturers', ['ManufacturerName_ID'], ['ID'], ondelete='CASCADE')
    op.create_index(op.f('IX_Microchips_Type_ID'), 'Microchips', ['Type_ID'], unique=False)
    op.create_index(op.f('IX_Microchips_TechnologyName_ID'), 'Microchips', ['TechnologyName_ID'], unique=False)
    op.create_index(op.f('IX_Microchips_ManufacturerName_ID'), 'Microchips', ['ManufacturerName_ID'], unique=False)
    op.create_index(op.f('IX_Microchips_Kind_ID'), 'Microchips', ['Kind_ID'], unique=False)
    op.alter_column('Microchips', 'Remark1',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'Qualication',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'Package',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'MemoryFormat',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'RadiationResistanceI',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'TechnologyName_ID',
               existing_type=sa.INTEGER(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('Microchips', 'BitDepthValue',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Microchips', 'Interfaces',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Manufacturers', 'ManufacturerName',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.create_index(op.f('IX_Diods_Type_ID'), 'Diods', ['Type_ID'], unique=False)
    op.create_index(op.f('IX_Diods_ManufacturerName_ID'), 'Diods', ['ManufacturerName_ID'], unique=False)
    op.create_index(op.f('IX_Diods_Kind_ID'), 'Diods', ['Kind_ID'], unique=False)
    op.alter_column('Diods', 'Remark2',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'Remark1',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'Package',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'QualicationЕС',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'QualicationSG',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('Diods', 'RadiationResistanceI',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               type_=sa.NVARCHAR(collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    op.alter_column('ComponentTypes', 'EnComponentType',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.alter_column('ComponentTypes', 'RuComponentType',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.alter_column('ComponentKinds', 'EnComponentKind',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.alter_column('ComponentKinds', 'RuComponentKind',
               existing_type=sa.NVARCHAR(length=450, collation='Cyrillic_General_CI_AS'),
               nullable=False)
    op.create_index(op.f('IX_Capacitors_Type_ID'), 'Capacitors', ['Type_ID'], unique=False)
    op.create_index(op.f('IX_Capacitors_ManufacturerName_ID'), 'Capacitors', ['ManufacturerName_ID'], unique=False)
    op.create_index(op.f('IX_Capacitors_Kind_ID'), 'Capacitors', ['Kind_ID'], unique=False)
    op.alter_column('Capacitors', 'MinVoltage',
               existing_type=sa.FLOAT(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
