"""date all orm models

Revision ID: 529819482e62
Revises: 613f90c7befe
Create Date: 2025-08-31 14:37:17.694061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529819482e62'
down_revision: Union[str, Sequence[str], None] = '613f90c7befe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Capacitors', sa.Column('Date', sa.DATE(), nullable=True))
    op.add_column('Diods', sa.Column('Date', sa.DATE(), nullable=True))
    op.alter_column('Microchips', 'Date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Resistors', 'Date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('Transistors', sa.Column('Date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transistors', 'Date')
    op.alter_column('Resistors', 'Date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Microchips', 'Date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('Diods', 'Date')
    op.drop_column('Capacitors', 'Date')
    # ### end Alembic commands ###
