"""date & default columns

Revision ID: 613f90c7befe
Revises: 0af868b75b7c
Create Date: 2025-08-29 20:48:27.935947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613f90c7befe'
down_revision: Union[str, Sequence[str], None] = '0af868b75b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Microchips', sa.Column('Date', sa.DATE(), nullable=True))
    op.add_column('Resistors', sa.Column('Date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resistors', 'Date')
    op.drop_column('Microchips', 'Date')
    # ### end Alembic commands ###
